"""prices.py — Price book loader.

Loads prices_data.json (generated by scripts/dump-prices.mjs from
public/lib/prices.js) and exposes the Prices dict plus pre-projected
default tables that the engine uses directly.

Mirrors: public/lib/cost-engine.js lines 28–91 (price-book loading
and _projectCategory / _stripPriceMeta helpers).
"""
from __future__ import annotations

import json
import pathlib
from typing import Any, Dict

_HERE = pathlib.Path(__file__).parent
PRICES_DATA_PATH = _HERE / "prices_data.json"

_raw: Dict[str, Any] = json.loads(PRICES_DATA_PATH.read_text())

# Remove the header metadata keys that dump-prices.mjs inserts
Prices: Dict[str, Any] = {
    k: v for k, v in _raw.items()
    if not k.startswith("_")
}

# ---------------------------------------------------------------------------
# Helpers mirroring _stripPriceMeta / _projectCategory in cost-engine.js
# ---------------------------------------------------------------------------
_DROP_META = {"source_url", "last_verified", "notes"}


def _strip_price_meta(entry: Dict[str, Any], include_provider: bool = False) -> Dict[str, Any]:
    """Mirror cost-engine.js _stripPriceMeta."""
    out: Dict[str, Any] = {}
    for k, v in (entry or {}).items():
        if k in _DROP_META:
            continue
        if k == "provider":
            if include_provider:
                out[k] = v
            continue
        out[k] = v
    return out


def _project_category(cat: str, include_provider: bool = False) -> Dict[str, Any]:
    """Mirror cost-engine.js _projectCategory."""
    out: Dict[str, Any] = {}
    for k, v in (Prices.get(cat) or {}).items():
        if not isinstance(v, dict):
            continue
        out[k] = _strip_price_meta(v, include_provider=include_provider)
    return out


# Pre-computed default tables (same names as in cost-engine.js)
DEFAULT_RATE_CARDS: Dict[str, Any] = _project_category("llm_models", include_provider=True)
DEFAULT_GPU_CATALOG: Dict[str, Any] = _project_category("gpu_instances", include_provider=False)
DEFAULT_COST_MODES: Dict[str, Any] = _project_category("self_host_cost_modes", include_provider=False)

DEFAULT_TIER_MULTIPLIERS: Dict[str, float] = {
    k: v["multiplier"]
    for k, v in (Prices.get("tier_multipliers") or {}).items()
    if isinstance(v, dict) and "multiplier" in v
}

FEDRAMP_MULTIPLIERS: Dict[str, float] = {
    k: v["multiplier"]
    for k, v in ((Prices.get("federal_multipliers") or {}).get("fedramp") or {}).items()
    if isinstance(v, dict) and "multiplier" in v
}

MULTI_REGION_MULTIPLIERS: Dict[str, float] = {
    k: v["multiplier"]
    for k, v in ((Prices.get("federal_multipliers") or {}).get("multi_region") or {}).items()
    if isinstance(v, dict) and "multiplier" in v
}
